### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by DenielWorld** [tedo0627/RedstoneCircuit#22]
All the bugs that I've found so far.

1: When a piston pushes another piston onto a different piston's arm server closes.

2: When a hopper has items in it, and gets pushed by a piston to be connected with a block that has an inventory, it does not transfer items.

3: If you take items out of the hopper while it is transferring them, the items get duped.

Most of these bugs can be critical for use on a server, please fix.

**Comment by tedo0627** [comment]
I did not understand about 1 and 2. I'm glad if you send me an error log or a photo.

Bug 3 is a pmmp specification. Please try to proliferate in survival mode. When the player is in survival mode, it appears to multiply, but it is not.

**Comment by DenielWorld** [comment]
1 means that if a piston, pushes the second piston towards the third activated piston the server crashes.

2 means that if a hopper is moved by piston towards any block with inventory, it does not transfer items.

**Comment by DenielWorld** [comment]
Ill try what you said about 3

**Comment by DenielWorld** [comment]
Yes, 3 seems like a visual glitch. Although the other 2 bugs are real.

**Comment by tedo0627** [comment]
After all I can not reproduce that state. I would be glad if you could send me a picture or video of that state.

**Comment by DenielWorld** [comment]
Do you have a email where I can provide the pictures?

**Comment by tedo0627** [comment]
tedosw1mpr1ver@gmail.com It is my mail address.

**Comment by DenielWorld** [comment]
Sent

**Comment by tedo0627** [comment]
ok

**Comment by tedo0627** [comment]
I was able to confirm bug 1. I will fix it.
But something like bug2 did not happen. I saw Item transferring from the hopper to the chest when I pull the lever. I will check just in case, is redstone plugin the latest?

**Comment by DenielWorld** [comment]
I believe so

**Comment by tedo0627** [comment]
I fixed bug 1.

**Comment by UladzimirPetrachkiu** [comment]
When i place piston on piston (horizontal) i've got this
error: "Call to undefined method redstone\blocks\BlockPistonarmcollision::getFace()" (EXCEPTION) in "plugins/RedstoneCircuit/src/redstone/blockEntities/BlockEntityPistonArm" at line 109.
Because BlockPistonarmcollision haven't getFace() method. Please add some like in other piston blocks or something

    public function getFace() : int {
        $damage = $this->getDamage();
        if ($damage == Facing::UP || $damage == Facing::DOWN) {
            return $damage;
        }
        return Facing::opposite($damage);
    }

**Comment by tedo0627** [comment]
I think fixed the bug, but has it not been fixed yet?

**Comment by DenielWorld** [comment]
What about 2?

**Comment by DenielWorld** [comment]
Piston bug still remains, I think the problem is that when a piston is pushed, it doesn't know what face side to set it to. So basically to fix that I think you should get the current face of the piston when it gets pushed by a different piston, and then set that face to the block that it gets moved to

**Comment by DenielWorld** [comment]
Bug 4> When an arrow out of dispenser hits an entity, server crashes
(I guess the same thing will happen with any of the projectiles thrown by the dispenser)

**Comment by tedo0627** [comment]
In the condition of the picture sent to me, I get no error. I'm glad if you send me a picture again under which condition an error occurs.
I could not confirm bug2 and bug4. Please pull out plugins other than redstone plugin.

**Comment by DenielWorld** [comment]
For bug 4 you need to get the arrow of the dispenser to hit someone, as for bug 2 I am going to check again

**Comment by tedo0627** [comment]
I tried on survival mode player and zombie but no errors occurred.

**Comment by DenielWorld** [comment]
I guess I could show you, could you get on my server?

**Comment by tedo0627** [comment]
yes

**Comment by tedo0627** [comment]
I am at your server now.

**Comment by tedo0627** [comment]
I fixed the piston bug. Please check once.

**Comment by DenielWorld** [comment]
I see, ill take a look. Please fix the FactionsPE problem though.

**Comment by tedo0627** [comment]
I fixed FactionsPE problem.

**Comment by DenielWorld** [comment]
Thank you

**Comment by DenielWorld** [comment]
Because of the factions fix dispensers cant do damage anymore
